"""
document_tools.py
-----------------
Defines the DocumentBuilder (runtime state), all agent tool definitions,
and the execute_tool dispatcher used by the agent service.

Tools exposed to the LLM:
  1. plan_document_outline  — creates the document structure first
  2. write_section          — writes one section with full Markdown content
  3. finalize_document      — compiles everything into the final document
"""

from __future__ import annotations

from datetime import datetime
from typing import Any


# ---------------------------------------------------------------------------
# Runtime document state
# ---------------------------------------------------------------------------


class DocumentBuilder:
    """Accumulates sections and compiles the final Markdown document."""

    def __init__(self, title: str, document_type: str, style: str) -> None:
        self.title = title
        self.document_type = document_type
        self.style = style
        self.outline: list[dict] = []
        self.sections: dict[str, dict] = {}  # section_id -> {heading, content, level}
        self.order: list[str] = []           # preserves insertion order
        self.finalized: bool = False
        self.final_document: str = ""

    # ------------------------------------------------------------------ tools

    def plan_outline(
        self, title: str, document_type: str, sections: list[dict]
    ) -> str:
        self.outline = sections
        # Seed order from the plan (write_section may add extras)
        self.order = [s["id"] for s in sections]
        return (
            f"Outline planned with {len(sections)} sections: "
            + ", ".join(f'"{s["heading"]}"' for s in sections)
        )

    def write_section(
        self,
        section_id: str,
        heading: str,
        content: str,
        level: int = 2,
    ) -> str:
        self.sections[section_id] = {
            "heading": heading,
            "content": content,
            "level": max(1, min(level, 4)),
        }
        if section_id not in self.order:
            self.order.append(section_id)
        words = len(content.split())
        return (
            f"Section \"{heading}\" written ({words} words, "
            f"{len(content)} chars)."
        )

    def compile_document(self) -> str:
        """Build the fully-formatted Markdown document from accumulated sections."""
        date_str = datetime.now().strftime("%B %d, %Y")
        parts: list[str] = []

        # ── Document header ─────────────────────────────────────────────────
        parts.append(f"# {self.title}\n")
        parts.append(
            f"> **Document Type:** {self.document_type.title()}"
            f" &nbsp;|&nbsp; **Style:** {self.style.title()}"
            f" &nbsp;|&nbsp; **Generated:** {date_str}\n"
        )
        parts.append("\n---\n")

        # ── Table of Contents ────────────────────────────────────────────────
        parts.append("## Table of Contents\n")
        counter = 1
        for section_id in self.order:
            if section_id not in self.sections:
                continue
            heading = self.sections[section_id]["heading"]
            anchor = (
                heading.lower()
                .replace(" ", "-")
                .replace(".", "")
                .replace(",", "")
                .replace("(", "")
                .replace(")", "")
            )
            parts.append(f"{counter}. [{heading}](#{anchor})\n")
            counter += 1
        parts.append("\n---\n")

        # ── Body sections ────────────────────────────────────────────────────
        for section_id in self.order:
            if section_id not in self.sections:
                continue
            sec = self.sections[section_id]
            marker = "#" * sec["level"]
            parts.append(f"\n{marker} {sec['heading']}\n\n")
            # Strip any leading heading line the LLM accidentally included in content
            content = sec["content"].strip()
            content_lines = content.splitlines()
            while content_lines and content_lines[0].lstrip().startswith("#"):
                content_lines.pop(0)
            parts.append("\n".join(content_lines).strip())
            parts.append("\n")

        # ── Footer ───────────────────────────────────────────────────────────
        parts.append("\n---\n")
        parts.append(
            f"*Document generated by the AI Document Agent &mdash; {date_str}*\n"
        )

        self.final_document = "\n".join(parts)
        self.finalized = True
        return self.final_document

    def finalize(self) -> str:
        return self.compile_document()


# ---------------------------------------------------------------------------
# Tool definitions (OpenAI function-calling schema)
# ---------------------------------------------------------------------------


def get_tool_definitions() -> list[dict]:
    return [
        {
            "type": "function",
            "function": {
                "name": "plan_document_outline",
                "description": (
                    "Plan the complete document structure BEFORE writing any content. "
                    "Call this FIRST. Define every section with a unique slug ID, "
                    "heading, and a short description of what it will cover."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "title": {
                            "type": "string",
                            "description": "The final document title.",
                        },
                        "document_type": {
                            "type": "string",
                            "description": (
                                "Type of document "
                                "(e.g. report, proposal, guide, business plan, white paper)."
                            ),
                        },
                        "sections": {
                            "type": "array",
                            "description": "Ordered list of all document sections.",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "type": "string",
                                        "description": (
                                            "Unique slug (kebab-case) for this section, "
                                            "e.g. 'executive-summary'."
                                        ),
                                    },
                                    "heading": {
                                        "type": "string",
                                        "description": "Section heading text.",
                                    },
                                    "description": {
                                        "type": "string",
                                        "description": (
                                            "One-sentence description of what this section covers."
                                        ),
                                    },
                                },
                                "required": ["id", "heading", "description"],
                            },
                        },
                    },
                    "required": ["title", "document_type", "sections"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "write_section",
                "description": (
                    "Write the full Markdown content for one document section. "
                    "Be thorough — 300 to 600 words per section. "
                    "Use rich Markdown: ### subheadings, **bold**, *italic*, "
                    "bullet lists ( - ), numbered lists, Markdown tables (| col |), "
                    "and blockquotes ( > ) for callouts, key insights, or tips. "
                    "Write every section defined in the outline."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "section_id": {
                            "type": "string",
                            "description": "The section slug as defined in the outline.",
                        },
                        "heading": {
                            "type": "string",
                            "description": "Section heading (matches the outline).",
                        },
                        "content": {
                            "type": "string",
                            "description": (
                                "Full Markdown content for this section. "
                                "Must be comprehensive (300+ words). "
                                "Use subsections (###), lists, tables, and blockquotes freely."
                            ),
                        },
                        "level": {
                            "type": "integer",
                            "description": (
                                "Heading level: 2 for top-level sections, "
                                "3 only for sub-sections."
                            ),
                        },
                    },
                    "required": ["section_id", "heading", "content"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "finalize_document",
                "description": (
                    "Compile and finalize the document. "
                    "Call this LAST, ONLY AFTER all sections have been written. "
                    "This assembles the table of contents, all sections, and the footer "
                    "into the complete, formatted document."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {},
                    "required": [],
                },
            },
        },
    ]


# ---------------------------------------------------------------------------
# Tool executor
# ---------------------------------------------------------------------------


def execute_tool(
    name: str,
    args: dict[str, Any],
    builder: DocumentBuilder,
) -> tuple[str, dict | None]:
    """
    Run a named tool against *builder*.
    Returns (result_string_for_llm, optional_sse_event_dict).
    """
    if name == "plan_document_outline":
        result = builder.plan_outline(
            title=args.get("title", builder.title),
            document_type=args.get("document_type", builder.document_type),
            sections=args.get("sections", []),
        )
        event = {
            "type": "outline_planned",
            "sections": [
                {"id": s["id"], "heading": s["heading"]}
                for s in args.get("sections", [])
            ],
        }
        return result, event

    elif name == "write_section":
        result = builder.write_section(
            section_id=args.get("section_id", ""),
            heading=args.get("heading", ""),
            content=args.get("content", ""),
            level=args.get("level", 2),
        )
        event = {
            "type": "section_written",
            "section_id": args.get("section_id"),
            "heading": args.get("heading"),
        }
        return result, event

    elif name == "finalize_document":
        result = builder.finalize()
        return result, None

    else:
        return f"Unknown tool: {name}", None
